# NumPy Day 2 Tasks Solutions

## Task 1.4.1

In [1]:
import numpy as np

matrix = np.random.randint(1, 101, (6, 6))

result = matrix[(matrix % 3 == 0) & (matrix % 5 == 0)]

print("Matrix:\n", matrix)
print("Divisible by both 3 and 5:\n", result)


Matrix:
 [[ 79  99  23  77  28  27]
 [ 29 100  57  35  39   6]
 [ 59  69  67  12  45  37]
 [ 92   9  80   1  44  79]
 [ 39  95  13  48  77  10]
 [ 34   9  96  81   2  85]]
Divisible by both 3 and 5:
 [45]


## Task 1.4.2

In [2]:
import numpy as np

arr = np.random.randint(1, 100, 10)

mean_val = arr.mean()

binary = np.where(arr < mean_val, 0, 1)

print("Array:", arr)
print("Mean:", mean_val)
print("Binarised:", binary)


Array: [92 26 56 77 30 25  1 83 30 87]
Mean: 50.7
Binarised: [1 0 1 1 0 0 0 1 0 1]


## Task 1.4.3

In [3]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

rows = [1, 3, 4]
cols = [0, 2, 4]

sub_matrix = arr[np.ix_(rows, cols)]

print("Original Matrix:\n", arr)
print("Sub Matrix:\n", sub_matrix)


Original Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Sub Matrix:
 [[ 5  7  9]
 [15 17 19]
 [20 22 24]]


## Task 1.4.4

In [4]:
import numpy as np

matrix = np.random.randint(1, 100, (4, 4))

row_sorted = np.sort(matrix, axis=1)

col_sorted = np.sort(matrix, axis=0)

print("Original Matrix:\n", matrix)
print("Row-wise Sorted:\n", row_sorted)
print("Column-wise Sorted:\n", col_sorted)


Original Matrix:
 [[70 28 83 86]
 [29 69 66 38]
 [13 21 66 62]
 [41 23 87 16]]
Row-wise Sorted:
 [[28 70 83 86]
 [29 38 66 69]
 [13 21 62 66]
 [16 23 41 87]]
Column-wise Sorted:
 [[13 21 66 16]
 [29 23 66 38]
 [41 28 83 62]
 [70 69 87 86]]


## Task 1.4.5

In [5]:
import numpy as np

scores = np.random.randint(0, 101, 15)

conditions = [
    scores >= 85,
    scores >= 70,
    scores >= 55,
    scores >= 40
]

grades = ['A', 'B', 'C', 'D']

result = np.select(conditions, grades, default='F')

print("Scores:", scores)
print("Grades:", result)


Scores: [ 0 91 53 67 18 51  8  7 94 78 53 95 71 74 77]
Grades: ['F' 'A' 'D' 'C' 'F' 'D' 'F' 'F' 'A' 'B' 'D' 'A' 'B' 'B' 'B']


## Task 2.2.1

In [6]:
import numpy as np

matrix = np.random.randint(1, 20, (5, 4))

row_add = np.array([1, 2, 3, 4])

col_sub = np.array([10, 20, 30, 40, 50]).reshape(5, 1)

result = matrix + row_add - col_sub

print("Original Matrix:\n", matrix)
print("Result:\n", result)


Original Matrix:
 [[15 12  9 18]
 [ 9 10 18 13]
 [13  8 12 13]
 [13 10  1 16]
 [ 9 15 16 18]]
Result:
 [[  6   4   2  12]
 [-10  -8   1  -3]
 [-16 -20 -15 -13]
 [-26 -28 -36 -20]
 [-40 -33 -31 -28]]


## Task 2.2.2

In [7]:
import numpy as np

matrix = np.random.randint(1, 100, (6, 4)).astype(float)

mean = matrix.mean(axis=0)

std = matrix.std(axis=0)

normalized = (matrix - mean) / std

print("Original Matrix:\n", matrix)
print("Normalized Matrix:\n", normalized)


Original Matrix:
 [[69.  5. 93. 80.]
 [62.  5. 58. 25.]
 [60. 26. 82. 39.]
 [87. 31. 95. 64.]
 [43. 88. 98. 97.]
 [80. 76. 79. 92.]]
Normalized Matrix:
 [[ 0.15176936 -1.03272654  0.65154633  0.51995991]
 [-0.33856241 -1.03272654 -1.93005233 -1.54735057]
 [-0.4786572  -0.38534573 -0.15981325 -1.02112608]
 [ 1.41262247 -0.23120744  0.79906625 -0.0814395 ]
 [-1.66946292  1.52596907  1.02034614  1.15894678]
 [ 0.9222907   1.15603718 -0.38109314  0.97100947]]


## Task 2.2.3

In [8]:
import numpy as np

points = np.array([2, 5, 8, 12, 20])

distance_matrix = np.abs(points[:, np.newaxis] - points)

print("Points:", points)
print("Distance Matrix:\n", distance_matrix)


Points: [ 2  5  8 12 20]
Distance Matrix:
 [[ 0  3  6 10 18]
 [ 3  0  3  7 15]
 [ 6  3  0  4 12]
 [10  7  4  0  8]
 [18 15 12  8  0]]


## Task 3.3.1

In [9]:
import numpy as np

A = np.random.rand(3, 3)

A_inv = np.linalg.inv(A)

identity = A @ A_inv

print("A:\n", A)
print("A @ inv(A):\n", identity)

print("Is Close to Identity?",
      np.allclose(identity, np.eye(3)))


A:
 [[0.38556087 0.83830966 0.96208802]
 [0.64738756 0.94355646 0.31032973]
 [0.81305022 0.75894537 0.16340857]]
A @ inv(A):
 [[ 1.00000000e+00 -1.63761508e-16  1.67454463e-16]
 [ 1.34492613e-16  1.00000000e+00  1.99682892e-16]
 [ 2.09778634e-17 -4.21398039e-16  1.00000000e+00]]
Is Close to Identity? True


## Task 3.3.2

In [10]:
import numpy as np

A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 10])

solution = np.linalg.solve(A, b)

print("Solution:", solution)

print("Verification:", A @ solution)


Solution: [1. 3.]
Verification: [ 5. 10.]


## Task 3.3.3

In [11]:
import numpy as np

A = np.random.rand(3, 3)

S = A.T @ A

eigenvalues, eigenvectors = np.linalg.eig(S)

print("Symmetric Matrix:\n", S)

print("Eigenvalues:\n", eigenvalues)

print("All Non-negative?",
      np.all(eigenvalues >= 0))


Symmetric Matrix:
 [[1.26125152 0.76144833 0.65724156]
 [0.76144833 0.62553297 0.72525267]
 [0.65724156 0.72525267 0.99389334]]
Eigenvalues:
 [2.41409002e+00 4.66436622e-01 1.51177239e-04]
All Non-negative? True


## Task 3.3.4

In [12]:
import numpy as np

v1 = np.random.rand(5)

v2 = np.random.rand(5)

u1 = v1 / np.linalg.norm(v1)

u2 = v2 / np.linalg.norm(v2)

dot_product = np.dot(u1, u2)

print("Unit Vector 1:", u1)
print("Unit Vector 2:", u2)

print("Dot Product:", dot_product)


Unit Vector 1: [0.20814226 0.82741168 0.29428395 0.19599271 0.38347166]
Unit Vector 2: [0.36115414 0.62705399 0.04645985 0.67208905 0.15002924]
Dot Product: 0.7969321411695358
